# Análisis exploratorio de Sabores de Archipilego

In [1]:
# Librería 
import pandas as pd
import numpy as np 
import os

import sys
sys.path.append('..')
from src import soporte_analisis as sp

In [2]:
# Abrir archivos
ruta_carpeta = "../data" 
dataframes = sp.abrir_archivos_en_carpeta(ruta_carpeta)

In [3]:
# Visualizar archivos
for nombre, df in dataframes.items():
    print(f"\n🗂️ Archivo: {nombre}")
    display(df.head()) 
    df.info()
    print('DUPLICADOS')
    display(df.duplicated().sum())
    columnas_filtradas = [col for col in df.columns if df[col].nunique() < 15]
    if columnas_filtradas:
        print("\n📊 Valores únicos en columnas con menos de 10 valores únicos:")
        for col in columnas_filtradas:
            print(f"🔹 {col}: {df[col].unique()}")
    else:
        print("⚠️ No hay columnas con menos de 10 valores únicos.")
    
    print('_____________________________________________')

🗂️ Archivo: campaigns_data.csv

,Campaña ID,Fecha Inicio,Fecha Fin,Tipo de Campaña,Presupuesto,Impressions,Clics,Conversiones,ROI
0,1,Email Marketing,2025-01-23,2025-02-03,1471.17,34687,2193,156,2.84
1,2,Anuncios en Google,2025-01-12,2025-01-21,1523.76,26854,2337,187,4.03
2,3,Anuncios en Google,2025-01-31,2025-02-10,1849.85,25229,1261,93,2.20
3,4,Anuncios en Google,2025-02-13,2025-01-07,737.22,20616,2199,206,4.27
4,5,Redes Sociales,2025-02-08,2025-01-30,1849.47,24978,2660,108,3.93

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Campaña ID       50 non-null     int64
 1   Fecha Inicio     50 non-null     object
 2   Fecha Fin        50 non-null     object
 3   Tipo de Campaña  50 non-null     object
 4   Presupuesto      50 non-null     float64
 5   Impressions      50 non-null     int64
 6   Clics            50 non-null     int64
 7   Conversiones     50 non-null     int64
 8   ROI              50 non-null     float64
dtypes: float64(2), int64(4), object(3)
memory usage: 3.6+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Fecha Inicio: ['Email Marketing' 'Anuncios en Google' 'Redes Sociales']
_____________________________________________

🗂️ Archivo: clients_data.csv

,ID Cliente,Nombre,Edad,Género,Ubicación,Frecuencia de compra
0,1,Erik Li,32,F,Douglasville,VIP
1,2,Peter Villarreal,49,F,Richardborough,Ocasional
2,3,Michelle Hanson,36,F,North Raymondville,Ocasional
3,4,Andrew Johnston,45,F,Port Grantland,Recurrente
4,5,Robert Rodriguez,46,F,Port Ethanchester,Ocasional

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID Cliente            100 non-null    int64
 1   Nombre                100 non-null    object
 2   Edad                  100 non-null    int64
 3   Género                100 non-null    object
 4   Ubicación             100 non-null    object
 5   Frecuencia de compra  100 non-null    object
dtypes: int64(2), object(4)
memory usage: 4.8+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Género: ['F' 'M']
🔹 Frecuencia de compra: ['VIP' 'Ocasional' 'Recurrente']
_____________________________________________

🗂️ Archivo: inventory_data.csv

,ID Producto,Nombre,Stock Inicial,Stock Actual,Productos Agotados
0,1,Almogrote,79,18,No
1,2,Queso Majorero,68,9,No
2,3,Licor Plátano de Canarias,61,22,No
3,4,Gofio,94,11,No
4,5,Vino Tinto Canario,111,96,No

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Producto         10 non-null     int64
 1   Nombre              10 non-null     object
 2   Stock Inicial       10 non-null     int64
 3   Stock Actual        10 non-null     int64
 4   Productos Agotados  10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 ID Producto: [ 1  2  3  4  5  6  7  8  9 10]
🔹 Nombre: ['Almogrote' 'Queso Majorero' 'Licor Plátano de Canarias' 'Gofio'
 'Vino Tinto Canario' 'Aceite de Oliva' 'Papas Negras de Canarias'
 'Dulce de Membrillo' 'Miel de Palma' 'Mojo Picón']
🔹 Stock Inicial: [ 79  68  61  94 111 144  98 139]
🔹 Stock Actual: [18  9 22 11 96 82 59 78 79 17]
🔹 Productos Agotados: ['No']
_____________________________________________

🗂️ Archivo: sales_data.csv

,Fecha,Producto,Cantidad,Precio Unitario,Total Venta
0,2025-01-31,Miel de Palma,2,29.42,58.84
1,2025-02-15,Gofio,5,10.71,53.55
2,2025-01-31,Aceite de Oliva,2,12.64,25.27
3,2025-01-29,Papas Negras de Canarias,1,18.01,18.01
4,2025-02-14,Dulce de Membrillo,3,17.29,51.87

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            200 non-null    object
 1   Producto         200 non-null    object
 2   Cantidad         200 non-null    int64
 3   Precio Unitario  200 non-null    float64
 4   Total Venta      200 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 7.9+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Producto: ['Miel de Palma' 'Gofio' 'Aceite de Oliva' 'Papas Negras de Canarias'
 'Dulce de Membrillo' 'Queso Majorero' 'Licor Plátano de Canarias'
 'Mojo Picón' 'Vino Tinto Canario' 'Almogrote']
🔹 Cantidad: [2 5 1 3 4]
_____________________________________________

🗂️ Archivo: satisfaction_data.csv

,ID Cliente,Producto,Calificación,Comentarios
0,19,Miel de Palma,5,Thing throughout research draw either.
1,54,Queso Majorero,2,Go sign car service vote seek chair.
2,7,Queso Majorero,1,Example human far skill Mr.
3,1,Miel de Palma,2,National yes member hair.
4,1,Dulce de Membrillo,2,Sit worker majority top animal show.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID Cliente    100 non-null    int64
 1   Producto      100 non-null    object
 2   Calificación  100 non-null    int64
 3   Comentarios   100 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.3+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Producto: ['Miel de Palma' 'Queso Majorero' 'Dulce de Membrillo' 'Aceite de Oliva'
 'Vino Tinto Canario' 'Papas Negras de Canarias' 'Mojo Picón' 'Gofio'
 'Almogrote' 'Licor Plátano de Canarias']
🔹 Calificación: [5 2 1 4 3]
_____________________________________________

🗂️ Archivo: traffic_data.csv

,Fecha,Página de Aterrizaje,Duración (min),Tasa de Rebote,Fuente,Dispositivo
0,2025-02-22,Dulce de Membrillo,3,73.53,Redes Sociales,Móvil
1,2025-02-14,Gofio,6,75.08,Pagado,Tablet
2,2025-01-27,Licor Plátano de Canarias,2,48.34,Referidos,Tablet
3,2025-01-03,Página de Inicio,6,62.93,Pagado,Desktop
4,2025-02-24,Licor Plátano de Canarias,4,63.19,Pagado,Móvil

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fecha                 150 non-null    object
 1   Página de Aterrizaje  150 non-null    object
 2   Duración (min)        150 non-null    int64
 3   Tasa de Rebote        150 non-null    float64
 4   Fuente                150 non-null    object
 5   Dispositivo           150 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 7.2+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Página de Aterrizaje: ['Dulce de Membrillo' 'Gofio' 'Licor Plátano de Canarias'
 'Página de Inicio' 'Papas Negras de Canarias' 'Mojo Picón'
 'Miel de Palma' 'Aceite de Oliva' 'Vino Tinto Canario' 'Almogrote'
 'Queso Majorero']
🔹 Duración (min): [ 3  6  2  4  8  9 10  1  5  7]
🔹 Fuente: ['Redes Sociales' 'Pagado' 'Referidos' 'Orgánico']
🔹 Dispositivo: ['Móvil' 'Tablet' 'Desktop']
_____________________________________________

# Cambiar los campos tipo fecha y visualizar como estan estructuradas por si necesitan cambios en el código de generacion de datos.

In [4]:
dataframes = {key: sp.convertir_columnas(df) for key, df in dataframes.items()}

In [5]:
# Intentar convertir columnas de fecha antes de filtrarlas
for key, df in dataframes.items():
    if df is not None and isinstance(df, pd.DataFrame):  # Verifica que df no sea None y sea un DataFrame
        for col in df.columns:
            if df[col].dtype == "object":  # Si la columna es tipo string
                try:
                    df[col] = pd.to_datetime(df[col], errors='coerce')  # Intenta convertir a datetime
                except:
                    pass  # Si falla, sigue con la siguiente

# Ver columnas de tipo fecha en cada DataFrame del diccionario
for key, df in dataframes.items():
    if df is not None and isinstance(df, pd.DataFrame):  # Verifica que df sea un DataFrame válido
        date_columns = [col for col in df.columns if pd.api.types.is_datetime64_any_dtype(df[col])]